#!/usr/bin/env node
/** 开发期启动：在 dsh checkout 里运行 pnpm dsh web --patch <本工程 overlay>。 */
import { spawnSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const dshRoot = resolve(
  process.env.DSH_ROOT ?? join(process.env.HOME ?? '', 'git', 'deepseek-harness'),
)
const overlayPath = join(projectRoot, '.overlay.dev.yml')
const entry = join(projectRoot, 'src', 'index.ts')

const overlay = [
  '# Generated by scripts/dev.mjs — do not edit.',
  // 正式安装（dsh plugin add）的行先于本 overlay 应用；disable 压掉它，
  // 避免同一插件双实例。profile 未安装该插件时此 patch 匹配不到，
  // 仅产生一条 skipped 警告，无害。dev 行用独立 id，不与被禁用行冲突。
  '- id: dsh-plan-and-execute',
  '  disabled: true',
  '- insert:',
  '    - id: dsh-plan-and-execute-dev',
  `      name: ${JSON.stringify(entry)}`,
  '      config:',
  "        onStepFailure: 'pause'",
  '        maxAutoRecoveries: 2',
  "        planDir: '.pae'",
  '',
].join('\n')

writeFileSync(overlayPath, overlay)
const args = ['dsh', 'web', '--patch', overlayPath, ...process.argv.slice(2)]
console.log(`[dev] cwd=${dshRoot}\n[dev] pnpm ${args.join(' ')}`)
const result = spawnSync('pnpm', args, { cwd: dshRoot, stdio: 'inherit' })
process.exit(result.status ?? 1)
