#!/usr/bin/env node
/** 开发期启动：在 dsh checkout 里运行 pnpm dsh web --patch <本工程 overlay>。 */
import { spawnSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const dshRoot = resolve(
  process.env.DSH_ROOT ?? join(process.env.HOME ?? '', 'git', 'deepseek-harness'),
)
const overlayPath = join(projectRoot, '.overlay.dev.yml')
const entry = join(projectRoot, 'src', 'index.ts')

const overlay = [
  '# Generated by scripts/dev.mjs — do not edit.',
  '- insert:',
  '    - id: dsh-plan-and-execute',
  `      name: ${JSON.stringify(entry)}`,
  '      config:',
  "        onStepFailure: 'pause'",
  '        maxAutoRecoveries: 2',
  "        planDir: '.pae'",
  '',
].join('\n')

writeFileSync(overlayPath, overlay)
const args = ['dsh', 'web', '--patch', overlayPath, ...process.argv.slice(2)]
console.log(`[dev] cwd=${dshRoot}\n[dev] pnpm ${args.join(' ')}`)
const result = spawnSync('pnpm', args, { cwd: dshRoot, stdio: 'inherit' })
process.exit(result.status ?? 1)
